version: "3"
services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - orfeodb:/var/lib/postgresql/data
      - ./instalacion/orfeo.sql:/docker-entrypoint-initdb.d/orfeo.sql
    container_name: ${DATABASE_HOST}
  application:
    build:
      context: docker/
    restart: always
    ports:
      - ${PORT}:80
    volumes:
      - ./:/var/www/html
      - ./docker/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - database
    container_name: orfeo.app
volumes:
  orfeodb: {}
